ice:
  image: jimroth/ice:latest
  command: | 
    -Djava.net.preferIPv4Stack=true
    -Djava.net.preferIPv4Addresses
    -Duser.timezone=UTC
    run-app
  volumes:
    - ./ice/assets/ice.properties:/opt/ice/src/java/ice.properties
  log_driver: "json-file"
  log_opt:
    max-size: "10m"
    max-file: "3"
nginx-vouch:
  image: jimroth/nginx-vouch:latest
  command: nginx -g "daemon off;"
  volumes:
    - ./nginx-vouch/assets/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx-vouch/assets/nginx.conf:/etc/nginx/nginx.conf
    - ./vouch/assets/static:/site/static
  ports:
    - "80:80"
    - "8000:8000"
  links:
    - ice:ice
    - vouch:vouch
  log_driver: "json-file"
  log_opt:
    max-size: "10m"
    max-file: "3"
vouch:
  image: voucher/vouch-proxy:0.5.3
  volumes:
    - ./vouch/assets/config:/config
    - ./vouch/assets/data:/data
  log_driver: "json-file"
  log_opt:
    max-size: "10m"
    max-file: "3"
